### ISSUE TITLE
consulta url's byma

### ISSUE THREAD

**Issue by joaquindelacorte** [franco-lamas/PyOBD#1]
Buenas Franco,  Como estas?
Disculpa las molestias, solo queria consultarte si tenes disponible o sabes donde podria obtener la url de la api BYMA que contenga los valores de futuros/ derivados.
ejemplo: https://open.bymadata.com.ar/vanoms-be-core/rest/api/bymadata/free/futuros
el ejemplo no es valido. 
O si tenes un listado con todas las urls disponibles de la API
Desde ya, muchas gracias.
Saludos
Joaquin

**Comment by franco-lamas** [comment]
Como estas? 
Para la segunda semana de Noviembre podría agregar un método en la librería que traiga las cotizaciones tanto de futuros. Ya existe un método para la cotización de opciones (get_options).

Gracias por el interés en la librería.
Saludos

**Comment by joaquindelacorte** [comment]
Muchas gracias Franco!.
Excelente trabajo

**Comment by franco-lamas** [comment]
Liberada la versión 0.1.8 de la libreria, las cotizaciones estan disponibles via get_futures().
Como todas las funciones luego de las 4am deja de funcionar hasta que abra el mercado.
