### ISSUE TITLE
Problemas con la descarga de algunas series

### ISSUE THREAD

**Issue by FedericoBohl** [franco-lamas/PyOBD#3]
Hola! Estoy utilizando la librería con mi script y note que prácticamente varias de las series de activos que se descargan fallan con excepción de los índices y de los cedears. Por otro lado, a veces el dataframe de los bonos corporativos se descarga pero con las celdas vacías. Esto me viene pasando hace como una semana y ya he probado con aislar el código para ver si el problema era mi script y aún así sigue fallando. Los errores varían según que serie deseo descargar.

**Comment by franco-lamas** [comment]
¿Como estas Federico? En este momento me encuetro trabajando en una migración hacia GitLab para mejorar el proceso de CI/CD. Me comentaron por Telegram del problema y posibles soluciones, apenas este resuelto te contacto.

Gracias por utilizar la libreria y ayudar a mejorarla, saludos.

**Comment by franco-lamas** [comment]
Perdon por la demora, recien lance la version 0.1.9-rc3 disponible desde PyPi via "pip install --upgrade pyobd==0.1.9rc3" solucionando el problema con el panel de coorporativos. El problema de las series historicas queda para el RC4

**Comment by franco-lamas** [comment]
Revisando el tema, las fallas en históricos son un problema de BYMA. Te recomiendo usar la conexión a Rava mediante la librería [Fallen](https://github.com/franco-lamas/Fallen).
